name: Bug report 🐛
description:
  Something not working as expected? This is the place to report your issue.
title: '[Bug]: '
labels: 'type: bug 🐛'
body:
  - type: markdown
    attributes:
      value: '## Welcome!'
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report.
  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package(s) are you using?
      multiple: true
      options:
        - 'made-design-tokens'
        - 'made-css'
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser(s) are you experiencing the issue?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge
  - type: input
    id: version
    attributes:
      label: Package version
      description: 'Which version(s) are you using?'
      placeholder: e.g. v2.0.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "Tell us more about the problem that you're running into"
      placeholder: What did you see? What did you expect to see?
    validations:
      required: true
    validations:
      required: true
  - type: input
    id: example-url
    attributes:
      label: Reproduction/example
      description: |
        Please send us a code example for us to debug and investigate the issue
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description:
        'How do we reproduce the error you described using the
        reproduction/example link above?'
    validations:
      required: true
